// Heurísticas puras de clasificación de seguidores — sin DB ni red, testeables en aislado.
// `follower` es el objeto YA NORMALIZADO (mismos campos que FollowerSnapshot), no el user object crudo de X.

function esAvatarPorDefecto(profileImageUrl, config) {
  return config.followerAnalysis.heuristics.defaultAvatarUrlPattern.test(profileImageUrl || '');
}

function patronUsernameAutogenerado(username, config) {
  return config.followerAnalysis.heuristics.suspicious.usernamePattern.test(username || '');
}

function esVacia(follower, config) {
  const { maxFollowerCount, maxPostCount } = config.followerAnalysis.heuristics.emptyThresholds;
  return (follower.follower_count ?? 0) <= maxFollowerCount && (follower.post_count ?? 0) <= maxPostCount;
}

function calcularScoreSospecha(follower, config) {
  const { weights, thresholds } = config.followerAnalysis.heuristics.suspicious;
  let score = 0;
  const reasons = [];

  if ((follower.follower_count ?? 0) < thresholds.lowFollowerCount) {
    score += weights.lowFollowerCount;
    reasons.push('low_follower_count');
  }

  if ((follower.post_count ?? 0) < thresholds.lowActivity) {
    score += weights.lowActivity;
    reasons.push('low_activity');
  }

  if (follower.account_created_at) {
    const ageDias = (Date.now() - new Date(follower.account_created_at).getTime()) / 86_400_000;
    if (ageDias >= thresholds.minAccountAgeDaysForRatioCheck) {
      const postsPorDia = (follower.post_count ?? 0) / ageDias;
      if (postsPorDia < thresholds.minExpectedPostsPerDay) {
        score += weights.ageActivityRatio;
        reasons.push('age_activity_ratio');
      }
    }
  }

  if (patronUsernameAutogenerado(follower.username, config)) {
    score += weights.autogeneratedUsername;
    reasons.push('autogenerated_username');
  }

  if (follower.is_default_avatar) {
    score += weights.defaultAvatar;
    reasons.push('default_avatar');
  }

  return { score, reasons };
}

function clasificarFollower(follower, config) {
  const { score, reasons } = calcularScoreSospecha(follower, config);
  const { scoreCutoff } = config.followerAnalysis.heuristics.suspicious;
  return {
    is_empty: esVacia(follower, config),
    suspicion_score: score,
    is_suspicious: score >= scoreCutoff,
    reasons,
  };
}

module.exports = {
  esAvatarPorDefecto,
  patronUsernameAutogenerado,
  esVacia,
  calcularScoreSospecha,
  clasificarFollower,
};
