import React, { useEffect, useRef, useState } from 'react';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip,
  ResponsiveContainer, Cell,
} from 'recharts';
import * as htmlToImage from 'html-to-image';
import jsPDF from 'jspdf';
import {
  ejecutarAnalisis, obtenerEstadoAnalisis, obtenerResultadosAnalisis,
} from '../api/botAnalysis';

const REASON_LABEL = {
  low_follower_count:     'Pocos seguidores',
  low_activity:            'Poca actividad',
  age_activity_ratio:      'Inactiva para su antigüedad',
  autogenerated_username:  'Username autogenerado',
  default_avatar:          'Avatar por defecto',
};

const POLL_MS = 1500;

export default function BotsTab({ cuentaId }) {
  const [run, setRun]                       = useState(null);
  const [resultados, setResultados]         = useState(null);
  const [cargandoInicial, setCargandoInicial] = useState(true);
  const [cargandoResultados, setCargandoResultados] = useState(false);
  const [ejecutando, setEjecutando]         = useState(false);
  const [budgetInput, setBudgetInput]       = useState('5');
  const [error, setError]                   = useState(null);
  const [exportando, setExportando]         = useState(false);

  const montadoRef      = useRef(false);
  const timeoutRef      = useRef(null);
  const resultadosRef   = useRef(null);

  useEffect(() => {
    montadoRef.current = true;
    (async () => {
      setCargandoInicial(true);
      try {
        const { run: r } = await obtenerEstadoAnalisis(cuentaId);
        if (!montadoRef.current) return;
        setRun(r);
        if (r?.status === 'en_progreso') {
          setEjecutando(true);
          cicloEjecutar();
        } else if (r?.status === 'completado') {
          cargarResultados(r._id);
        }
      } finally {
        if (montadoRef.current) setCargandoInicial(false);
      }
    })();
    return () => {
      montadoRef.current = false;
      if (timeoutRef.current) clearTimeout(timeoutRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [cuentaId]);

  async function cargarResultados(runId) {
    setCargandoResultados(true);
    try {
      const data = await obtenerResultadosAnalisis(cuentaId, runId);
      if (montadoRef.current) setResultados(data);
    } finally {
      if (montadoRef.current) setCargandoResultados(false);
    }
  }

  async function cicloEjecutar(budgetUsd) {
    setError(null);
    try {
      const { run: nuevoRun } = await ejecutarAnalisis(cuentaId, budgetUsd);
      if (!montadoRef.current) return;
      setRun(nuevoRun);
      if (nuevoRun.status === 'en_progreso') {
        timeoutRef.current = setTimeout(() => cicloEjecutar(), POLL_MS);
      } else {
        setEjecutando(false);
        if (nuevoRun.status === 'completado') cargarResultados(nuevoRun._id);
      }
    } catch (err) {
      if (!montadoRef.current) return;
      setError(err.response?.data?.mensaje || 'Error al ejecutar el análisis.');
      setEjecutando(false);
    }
  }

  function iniciar(e) {
    e.preventDefault();
    const monto = Number(budgetInput);
    if (!(monto > 0)) return;
    setEjecutando(true);
    setResultados(null);
    cicloEjecutar(monto);
  }

  async function exportar(formato) {
    if (!resultadosRef.current) return;
    setExportando(true);
    try {
      const dataUrl = await htmlToImage.toPng(resultadosRef.current, { backgroundColor: '#F4F6FA', pixelRatio: 2 });
      if (formato === 'png') {
        const link = document.createElement('a');
        link.download = `analisis-bots-${cuentaId}.png`;
        link.href = dataUrl;
        link.click();
      } else {
        const img = new Image();
        img.src = dataUrl;
        await new Promise(resolve => { img.onload = resolve; });
        const pdf = new jsPDF({
          orientation: img.width > img.height ? 'landscape' : 'portrait',
          unit: 'px', format: [img.width, img.height],
        });
        pdf.addImage(dataUrl, 'PNG', 0, 0, img.width, img.height);
        pdf.save(`analisis-bots-${cuentaId}.pdf`);
      }
    } catch {
      setError('No se pudo generar el archivo de exportación.');
    } finally {
      setExportando(false);
    }
  }

  if (cargandoInicial) {
    return <p style={{ color: 'var(--color-texto-secundario)', fontSize: '0.85rem' }}>Cargando estado...</p>;
  }

  const gastoPct = run?.budget_usd > 0 ? Math.min(100, (run.spent_usd / run.budget_usd) * 100) : 0;
  const maxMes = resultados ? Math.max(...resultados.por_mes_creacion.map(m => m.cantidad), 1) : 1;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>

      {/* ── Panel de control ─────────────────────────── */}
      <div style={card}>
        <SectionTitle>Análisis de bots / seguidores sospechosos</SectionTitle>
        <p style={{ fontSize: '0.83rem', color: 'var(--color-texto-secundario)', marginBottom: 16 }}>
          Trae seguidores reales de la cuenta (owned reads, $0.001 c/u) hasta agotar el presupuesto que definas.
        </p>

        {run?.status === 'en_progreso' ? (
          <div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.82rem', marginBottom: 6 }}>
              <span>Gasto: <strong>{fmtUsd(run.spent_usd)}</strong> / {fmtUsd(run.budget_usd)}</span>
              <span style={{ color: 'var(--color-texto-secundario)' }}>{run.followers_fetched} seguidores traídos</span>
            </div>
            <Barra pct={gastoPct} color="var(--color-primario)" />
            <p style={{ fontSize: '0.78rem', color: 'var(--color-texto-secundario)', marginTop: 10 }}>
              Corriendo... la corrida continúa automáticamente en tandas hasta terminar o agotar el presupuesto.
            </p>
          </div>
        ) : (
          <form onSubmit={iniciar} style={{ display: 'flex', gap: 10, alignItems: 'center', flexWrap: 'wrap' }}>
            <label style={{ fontSize: '0.85rem', color: 'var(--color-texto-secundario)' }}>Presupuesto (USD)</label>
            <input
              type="number" min="0.01" step="0.01" value={budgetInput}
              onChange={e => setBudgetInput(e.target.value)}
              style={{ width: 100, padding: '8px 10px', border: '1px solid #D1D5DB', borderRadius: 6, fontSize: '0.9rem', fontFamily: 'var(--fuente-base)' }}
            />
            <button type="submit" disabled={ejecutando} style={btnPrimario}>
              {run?.status === 'completado' || run?.status === 'error' ? 'Nuevo análisis' : 'Iniciar análisis'}
            </button>
          </form>
        )}

        {error && <p style={{ color: 'var(--color-acento)', fontSize: '0.83rem', marginTop: 12 }}>{error}</p>}
      </div>

      {/* ── Resultados ───────────────────────────────── */}
      {cargandoResultados && (
        <p style={{ color: 'var(--color-texto-secundario)', fontSize: '0.85rem' }}>Calculando resultados...</p>
      )}

      {resultados && !cargandoResultados && (
        <div ref={resultadosRef} style={{ display: 'flex', flexDirection: 'column', gap: 20, background: 'var(--color-fondo)' }}>

          {/* Stat cards */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(160px, 1fr))', gap: 14 }}>
            <StatCard label="Cobertura de la muestra" valor={`${Number(run.coverage_pct).toFixed(1)}%`} />
            <StatCard label="Seguidores traídos" valor={run.followers_fetched.toLocaleString('es-AR')} />
            <StatCard label="Cuentas vacías" valor={run.vacias_count.toLocaleString('es-AR')} alerta={run.vacias_count > 0} />
            <StatCard label="Cuentas sospechosas" valor={run.sospechosas_count.toLocaleString('es-AR')} alerta={run.sospechosas_count > 0} />
            <StatCard label="Estimado total (extrapolado)" valor={run.estimated_flagged_total.toLocaleString('es-AR')} alerta={run.estimated_flagged_total > 0} />
            <StatCard label="Costo estimado de bots" valor={fmtUsd(run.estimated_cost_flagged_usd)} alerta={run.estimated_cost_flagged_usd > 0} />
          </div>

          {/* BarChart mensual */}
          <div style={card}>
            <SectionTitle>Cuentas seguidoras por mes de creación</SectionTitle>
            {resultados.por_mes_creacion.length === 0 ? (
              <Empty />
            ) : (
              <ResponsiveContainer width="100%" height={180}>
                <BarChart data={resultados.por_mes_creacion} margin={{ top: 4, right: 8, left: -20, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#F5F5F5" vertical={false} />
                  <XAxis dataKey="mes" tick={{ fontSize: 9, fill: '#9E9E9E' }} />
                  <YAxis tick={{ fontSize: 9, fill: '#9E9E9E' }} />
                  <Tooltip
                    formatter={v => [v, 'Cuentas creadas']}
                    contentStyle={{ fontSize: '0.78rem', borderRadius: 6, border: '1px solid #E0E0E0' }}
                  />
                  <Bar dataKey="cantidad" radius={[3, 3, 0, 0]}>
                    {resultados.por_mes_creacion.map(m => (
                      <Cell key={m.mes} fill={m.cantidad === maxMes ? 'var(--color-acento)' : 'var(--color-primario)55'} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>

          {/* Top 10 */}
          <div style={card}>
            <SectionTitle>Top 10 seguidores por cantidad de seguidores</SectionTitle>
            {resultados.top10.length === 0 ? <Empty /> : (
              <div style={{ overflowX: 'auto' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse' }}>
                  <thead><tr>{['Usuario', 'Seguidores', 'Posts', 'Estado'].map(h => <th key={h} style={th}>{h}</th>)}</tr></thead>
                  <tbody>
                    {resultados.top10.map((s, i) => {
                      const estado = estadoFollower(s.flag);
                      return (
                        <tr key={s._id} style={{ borderTop: '1px solid #F3F4F6' }}>
                          <td style={td}>
                            <div style={{ fontWeight: 600, fontSize: '0.85rem' }}>{s.display_name || s.username}</div>
                            <div style={{ color: 'var(--color-texto-secundario)', fontSize: '0.76rem' }}>@{s.username}</div>
                          </td>
                          <td style={{ ...td, fontWeight: i === 0 ? 700 : 400 }}>{Number(s.follower_count).toLocaleString('es-AR')}</td>
                          <td style={{ ...td, color: 'var(--color-texto-secundario)' }}>{Number(s.post_count).toLocaleString('es-AR')}</td>
                          <td style={td}>
                            <span style={{ padding: '2px 8px', borderRadius: 10, fontSize: '0.72rem', fontWeight: 600, background: estado.bg, color: estado.color }}>
                              {estado.label}
                            </span>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Flagged list */}
          <div style={card}>
            <SectionTitle>
              Cuentas flageadas {resultados.flagged.total_count > 0 && `(${resultados.flagged.total_count})`}
            </SectionTitle>
            {resultados.flagged.items.length === 0 ? <Empty msg="No se flagueó ninguna cuenta en la muestra." /> : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {resultados.flagged.items.map(f => (
                  <div key={f.flag._id} style={{ display: 'flex', gap: 10, alignItems: 'center', borderBottom: '1px solid #F5F5F5', paddingBottom: 8 }}>
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <span style={{ fontWeight: 600, fontSize: '0.83rem' }}>{f.display_name || f.username}</span>
                      <span style={{ color: 'var(--color-texto-secundario)', fontSize: '0.76rem', marginLeft: 6 }}>@{f.username}</span>
                      <div style={{ marginTop: 4, display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                        {f.flag.reasons.map(r => (
                          <span key={r} style={{ fontSize: '0.68rem', padding: '2px 7px', borderRadius: 8, background: '#F3F4F6', color: 'var(--color-texto-secundario)' }}>
                            {REASON_LABEL[r] || r}
                          </span>
                        ))}
                      </div>
                    </div>
                    <div style={{ textAlign: 'right', fontSize: '0.78rem', color: 'var(--color-texto-secundario)' }}>
                      Score: <strong style={{ color: 'var(--color-acento)' }}>{f.flag.suspicion_score}</strong>
                    </div>
                  </div>
                ))}
                {resultados.flagged.total_count > resultados.flagged.items.length && (
                  <p style={{ fontSize: '0.76rem', color: 'var(--color-texto-secundario)' }}>
                    Mostrando {resultados.flagged.items.length} de {resultados.flagged.total_count}.
                  </p>
                )}
              </div>
            )}
          </div>
        </div>
      )}

      {resultados && !cargandoResultados && (
        <div style={{ display: 'flex', gap: 10 }}>
          <button type="button" onClick={() => exportar('png')} disabled={exportando} style={btnSecundario}>
            {exportando ? 'Exportando...' : 'Exportar PNG'}
          </button>
          <button type="button" onClick={() => exportar('pdf')} disabled={exportando} style={btnSecundario}>
            {exportando ? 'Exportando...' : 'Exportar PDF'}
          </button>
        </div>
      )}
    </div>
  );
}

function estadoFollower(flag) {
  if (!flag) return { label: 'Sin clasificar', bg: '#F3F4F6', color: '#6B7280' };
  if (flag.is_suspicious) return { label: 'Sospechosa', bg: '#FFEBEE', color: '#D62828' };
  if (flag.is_empty) return { label: 'Vacía', bg: '#FFF8E1', color: '#E0A106' };
  return { label: 'Normal', bg: '#E8F5E9', color: '#2E7D32' };
}

function Barra({ pct, color }) {
  return (
    <div style={{ height: 6, background: '#F0F0F0', borderRadius: 3, overflow: 'hidden' }}>
      <div style={{ height: '100%', width: `${pct}%`, background: color, borderRadius: 3, transition: 'width 0.4s ease' }} />
    </div>
  );
}

function SectionTitle({ children }) {
  return <h3 style={{ fontSize: '0.88rem', fontWeight: 700, color: 'var(--color-texto)', marginBottom: 14 }}>{children}</h3>;
}

function StatCard({ label, valor, alerta }) {
  return (
    <div style={{
      background: '#fff', borderRadius: 8, padding: '14px 18px', boxShadow: '0 1px 3px rgba(0,0,0,0.07)',
      borderLeft: `3px solid ${alerta ? 'var(--color-acento)' : 'var(--color-primario)'}`,
    }}>
      <div style={{ fontSize: '1.4rem', fontWeight: 700, color: alerta ? 'var(--color-acento)' : 'var(--color-texto)', lineHeight: 1 }}>
        {valor}
      </div>
      <div style={{ fontSize: '0.72rem', color: 'var(--color-texto-secundario)', marginTop: 5 }}>{label}</div>
    </div>
  );
}

function Empty({ msg = 'Sin datos suficientes.' }) {
  return <p style={{ fontSize: '0.82rem', color: 'var(--color-texto-secundario)' }}>{msg}</p>;
}

const fmtUsd = v => `$${Number(v ?? 0).toLocaleString('es-AR', { minimumFractionDigits: 2, maximumFractionDigits: 4 })}`;

const card = { background: '#fff', borderRadius: 10, padding: '18px 22px', boxShadow: '0 1px 4px rgba(0,0,0,0.06)' };
const th   = { textAlign: 'left', padding: '8px 10px', fontSize: '0.72rem', fontWeight: 600, color: 'var(--color-texto-secundario)', textTransform: 'uppercase', letterSpacing: '0.04em' };
const td   = { padding: '11px 10px', verticalAlign: 'middle' };
const btnPrimario = {
  background: 'var(--color-primario)', color: '#fff', border: 'none',
  borderRadius: 6, padding: '8px 18px', fontSize: '0.83rem',
  fontFamily: 'var(--fuente-base)', cursor: 'pointer', fontWeight: 600,
};
const btnSecundario = {
  background: '#fff', color: 'var(--color-primario)', border: '1px solid var(--color-primario)',
  borderRadius: 6, padding: '8px 18px', fontSize: '0.83rem',
  fontFamily: 'var(--fuente-base)', cursor: 'pointer', fontWeight: 600,
};
