require('dotenv').config();

module.exports = {
  port: parseInt(process.env.PORT || '3000', 10),
  jwt: {
    secret: process.env.JWT_SECRET || 'cambiar_esto_en_produccion',
    expiresIn: '7d',
  },
  tokenEncryptionKey: process.env.TOKEN_ENCRYPTION_KEY,
  frontendUrl: process.env.FRONTEND_URL || 'http://localhost:5173',
  backendUrl: process.env.BACKEND_URL || 'http://localhost:3000',
  collectorCron: process.env.COLLECTOR_CRON || '0 */6 * * *',

  followerAnalysis: {
    costPerProfileUsd:            parseFloat(process.env.BOT_ANALYSIS_COST_PER_PROFILE_USD || '0.001'),  // owned reads
    defaultBudgetUsd:              parseFloat(process.env.BOT_ANALYSIS_DEFAULT_BUDGET_USD || '5'),
    botPriceUsd:                   parseFloat(process.env.BOT_ANALYSIS_BOT_PRICE_USD || '2'),
    wallClockSafetyMarginSeconds:  parseInt(process.env.BOT_ANALYSIS_TIME_SAFETY_MARGIN_S || '250', 10),
    maxResultsHardCap: 1000,   // límite duro de la API de X, no es un valor de negocio

    heuristics: {
      emptyThresholds: { maxFollowerCount: 0, maxPostCount: 0 },

      suspicious: {
        scoreCutoff: 50,
        weights: {
          lowFollowerCount:      25,
          lowActivity:           20,
          ageActivityRatio:      20,
          autogeneratedUsername: 20,
          defaultAvatar:         15,
        },
        thresholds: {
          lowFollowerCount:               10,
          lowActivity:                     5,
          minAccountAgeDaysForRatioCheck: 30,
          minExpectedPostsPerDay:       0.01,
        },
        usernamePattern: /^[a-z]+\d{4,}$/i,
      },

      defaultAvatarUrlPattern: /default_profile_(images|normal)/i,
    },
  },
};
